# Generated by Django 4.2.3 on 2023-07-31 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='core/static/media/user.png', upload_to='core/static/media'),
        ),
    ]
